name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sportsacademy-artifact
        path: target/          
  
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=javareachabilityy -Dsonar.organization=javareachabilityy -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      env:
        GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build and Push Docker Image to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
       context: .
       file: Dockerfile
       push: true
       tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}sportsacademy-latest
      env:
        DOCKER_BUILDKIT: 1
# Add a new step to push the image to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Tag and Push Docker Image to Docker Hub
      run: |
        docker image tag ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}sportsacademy-latest ${{ github.repository_owner }}/sportsacademy-latest:v1
        docker image push ${{ github.repository_owner }}/sportsacademy-latest:v1

