name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_GHCR }}
    - name: Extract metadata (tags, labels) for Docker image
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}
    - name: Create Docker image
      uses: docker/create-image@v4
      with:
        context: .
        file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Push Docker image to GHCR
      uses: docker/push-action@v4
      with:
       context: .
       file: Dockerfile
       push: true
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
